export const POST_VISION="POST_VISION";
export const RECEIVE_VISION="RECEIVE_VISION";
export const POST_TRANSLATIONS="POST_TRANSLATIONS";
export const RECEIVE_TRANSLATIONS="RECEIVE_TRANSLATIONS";
export const CHANGE_LANGUAGE="CHANGE_LANGUAGE";
export const SET_NAVIGATOR_REFERENCE="SET_NAVIGATOR_REFERENCE";
export const HIDE_AR_LABEL="HIDE_AR_LABEL"
export const SHOW_AR_LABEL="SHOW_AR_LABEL"